import { test, expect } from '@playwright/test'

test('register, incorrect OTP, verified phone, address, reload, logout and login', async ({ page, request }) => {
  const email = `na-${crypto.randomUUID()}@example.com`
  const phone = '+8491' + String(Math.floor(1000000 + Math.random() * 8999999))
  await page.goto('/na')
  await expect(page).toHaveURL(/\/login$/)
  await page.screenshot({ path: 'test-results/account-login-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Chưa có tài khoản? Đăng ký' }).click()
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Mật khẩu', { exact: true }).fill('Local-test-password!123')
  await page.getByLabel('Nhập lại mật khẩu', { exact: true }).fill('Local-test-password!123')
  await page.getByRole('button', { name: 'Tạo tài khoản', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Xác minh điện thoại' })).toBeVisible()
  await page.getByLabel('Số điện thoại', { exact: true }).fill(phone)
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Gửi mã OTP', exact: true }).click()
  await expect(page.getByLabel('Mã OTP', { exact: true })).toBeVisible()
  const response = await request.get('http://127.0.0.1:9099/emulator/v1/projects/demo-na/verificationCodes')
  const codes = await response.json()
  const otp = codes.verificationCodes.find((value: { phoneNumber: string }) => value.phoneNumber === phone).code
  await page.getByLabel('Mã OTP', { exact: true }).fill(otp === '000000' ? '111111' : '000000')
  await page.getByRole('button', { name: 'Xác minh số điện thoại', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Mã OTP không đúng')
  await page.getByLabel('Mã OTP', { exact: true }).fill(otp)
  await page.getByRole('button', { name: 'Xác minh số điện thoại', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Giao đến địa chỉ của bạn' })).toBeVisible()
  await page.getByLabel('Tên người nhận').fill('Na Test')
  await page.getByLabel('Số nhà, tên đường').fill('123 Test Street')
  await page.getByLabel('Thành phố / địa phương').fill('Da Nang')
  await page.getByRole('button', { name: 'Lưu địa chỉ', exact: true }).click()
  await expect(page).toHaveURL(/\/na$/)
  await expect(page.getByRole('link', { name: 'Tài khoản & địa chỉ' })).toBeVisible()
  await page.reload()
  await page.getByRole('link', { name: 'Tài khoản & địa chỉ' }).click()
  await expect(page.getByLabel('Số nhà, tên đường')).toHaveValue('123 Test Street')
  await page.getByRole('button', { name: 'Đăng xuất', exact: true }).click()
  await page.getByLabel('Email', { exact: true }).fill(email)
  await page.getByLabel('Mật khẩu', { exact: true }).fill('wrong-password')
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.getByLabel('Mật khẩu', { exact: true }).fill('Local-test-password!123')
  await page.getByRole('button', { name: 'Đăng nhập', exact: true }).click()
  await expect(page.getByLabel('Số nhà, tên đường')).toHaveValue('123 Test Street')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/account-address-mobile.png', fullPage: true })
})

test('Google popup creates an account and still requires phone verification', async ({ page }) => {
  await page.goto('/login')
  const popupPromise = page.waitForEvent('popup')
  await page.getByRole('button', { name: 'Tiếp tục với Google' }).click()
  const popup = await popupPromise
  await popup.getByRole('button', { name: 'Add new account' }).click()
  await popup.locator('#email-input').fill(`google-${crypto.randomUUID()}@example.com`)
  await popup.locator('form button[type="submit"]').click()
  await expect(page.getByRole('heading', { name: 'Xác minh điện thoại' })).toBeVisible()
  await page.goto('/na')
  await expect(page.getByRole('heading', { name: 'Xác minh điện thoại' })).toBeVisible()
})
