import { expect, test } from '@playwright/test'

test('structured search honors a request budget without AI or a price mandate', async ({ page }) => {
  await page.goto('/na')
  await page.getByText('Structured search · works without AI', { exact: true }).click()
  await page.getByLabel('Product or asset', { exact: true }).fill('Jordan 1')
  await page.getByLabel('Maximum for this request (optional)').fill('200')
  await page.getByRole('button', { name: 'Search sources', exact: true }).click()
  await expect(page.getByText('Na could not verify enough current information', { exact: false })).toBeVisible()
  await expect(page.locator('.research-card')).toHaveCount(0)
  const discoveries = page.getByRole('region', { name: 'Search results awaiting verification' })
  await expect(discoveries).toBeVisible()
  await expect(discoveries.getByRole('link').first()).toBeVisible()
  await expect(discoveries.getByRole('button', { name: 'Approve', exact: true })).toHaveCount(0)
  await page.getByLabel('Maximum for this request (optional)').fill('300')
  await page.getByRole('button', { name: 'Search sources', exact: true }).click()
  await expect(page.locator('.research-card')).toHaveCount(1)
  await expect(page.locator('.research-card')).toContainText('242 USD')
  await page.getByRole('link', { name: 'My mandate', exact: true }).click()
  await expect(page.getByLabel('Maximum value (integer lamports)')).toHaveCount(0)
  await page.getByRole('button', { name: 'Generate extension pairing code' }).click()
  await expect(page.getByText('Paste into Na Extension within two minutes:', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'Revoke extension sessions' }).click()
  await expect(page.getByText('Paste into Na Extension within two minutes:', { exact: false })).toHaveCount(0)
})

test('research cards, decisions, persistent twin and safe authority handoff', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/na')
  await page.getByLabel('Your request to Na').fill('Find Gundam RX-78 under 1,000,000 VND from a reputable seller')
  await page.getByRole('button', { name: 'Send request', exact: true }).click()
  await expect(page.locator('.research-card')).toHaveCount(1)
  await expect(page.getByText('MOCK / DEV DATA', { exact: true })).toBeVisible()
  await expect(page.getByText('MOCK / DEV DATA', { exact: true })).toBeInViewport()
  await expect(page.locator('.research-card').first()).toContainText('Authenticity: UNKNOWN')
  await page.getByRole('button', { name: 'Approve', exact: true }).first().click()
  await expect(page.getByRole('region', { name: 'Selected research item' })).toContainText('review required')
  await expect(page.getByText('Approval preference saved.', { exact: false })).toBeVisible()
  await expect(page.getByRole('button', { name: /Send proposal to Na/ })).toHaveCount(0)
  await page.getByLabel('Your request to Na').fill('Find headphones under 100 USD')
  await page.getByRole('button', { name: 'Send request', exact: true }).click()
  await expect(page.locator('.research-card')).toHaveCount(2)
  const second = page.locator('.research-card').last()
  await second.getByRole('button', { name: 'Reject', exact: true }).click()
  await second.getByLabel('Reason (optional)').selectOption('Too expensive')
  await second.getByRole('button', { name: 'Save rejection' }).click()
  await expect(second).toContainText('Rejection saved')
  await page.getByRole('link', { name: 'Activity', exact: true }).click()
  await expect(page.getByText('Approval preference · MOCK DATA')).toBeVisible()
  await page.reload()
  await expect(page.getByText('Rejected recommendation · MOCK DATA')).toBeVisible()
  await page.getByRole('link', { name: 'My mandate', exact: true }).click()
  await page.getByLabel('Seller reputation importance').selectOption('high')
  await page.getByLabel('Preferred premium for a trusted seller (%)').fill('5')
  await page.getByRole('button', { name: 'Save research preferences' }).click()
  await expect(page.getByText('Research preferences saved.')).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Seller reputation importance')).toHaveValue('high')
  await expect(page.getByLabel('Preferred premium for a trusted seller (%)')).toHaveValue('5')
  expect(errors).toEqual([])
})

test('mobile research cards preserve sources, fit the screen and report failures', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/na')
  await page.getByLabel('Your request to Na').fill('Find headphones under 100 USD')
  await page.getByRole('button', { name: 'Send request', exact: true }).click()
  await expect(page.locator('.research-card')).toHaveCount(1)
  await expect(page.locator('.research-card').first().getByRole('link', { name: /View Product/ })).toHaveAttribute('href', /https:\/\/example.com\/gobuy-dev/)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/research-mobile.png', fullPage: true })
  await page.route('**/api/research/search', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"error":{"message":"Research unavailable"}}' }))
  await page.getByLabel('Your request to Na').fill('Find something else')
  await page.getByRole('button', { name: 'Send request', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Research unavailable')
  await expect(page.locator('.research-card')).toHaveCount(1)
})

test('unverified authenticity produces no selected product or approval action', async ({ page }) => {
  await page.goto('/na')
  await page.getByLabel('Your request to Na').fill('Find authentic Gundam RX-78 under 1,000,000 VND')
  await page.getByRole('button', { name: 'Send request', exact: true }).click()
  await expect(page.getByText('Na could not verify enough current information', { exact: false })).toBeVisible()
  await expect(page.locator('.research-card')).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Approve', exact: true })).toHaveCount(0)
})

test('missing search configuration explains setup instead of claiming no product exists', async ({ page }) => {
  await page.route('**/api/research/search', async route => {
    const response = await route.fetch(), result = await response.json()
    await route.fulfill({ response, json: { ...result, mode: 'real', status: 'SETUP_REQUIRED', recommendations: [], researchedCount: 0, eligibleCount: 0,
      summary: 'Live search is not connected yet. Na has not searched for this product, so this is not a no-match result.',
      nextStep: 'Connect an independent live search source in backend/.env, then restart the backend.', warnings: [], providers: [],
    } })
  })
  await page.goto('/na')
  await page.getByLabel('Your request to Na').fill('find me jordan 1 under 100 usd')
  await page.getByRole('button', { name: 'Send request', exact: true }).click()
  await expect(page.getByText('SEARCH NOT CONNECTED', { exact: true })).toBeVisible()
  await expect(page.getByText('Connect an independent live search source in backend/.env, then restart the backend.', { exact: true })).toBeVisible()
  await expect(page.locator('.research-card')).toHaveCount(0)
  await page.screenshot({ path: 'test-results/research-setup.png', fullPage: true })
})

test('budget follow-up retains the product and BUY reports blocked payment honestly', async ({ page }) => {
  await page.goto('/na')
  await page.getByLabel('Your request to Na').fill('Find Jordan 1 under 200 USD')
  await page.getByRole('button', { name: 'Send request', exact: true }).click()
  await expect(page.getByText('Na could not verify enough current information', { exact: false })).toBeVisible()
  await expect(page.locator('.research-card')).toHaveCount(0)
  await page.getByLabel('Your request to Na').fill('Okay, maximum 300 USD.')
  await page.getByRole('button', { name: 'Send request', exact: true }).click()
  await expect(page.locator('.research-card')).toHaveCount(1)
  await expect(page.locator('.research-card').last()).toContainText('Jordan 1')
  await expect(page.locator('.research-card').last()).toContainText('242 USD')
  await page.getByLabel('Your request to Na').fill('Buy legit Jordan 1 Chicago size 42.5. Maximum 1 SOL.')
  await page.getByRole('button', { name: 'Send request', exact: true }).click()
  await expect(page.getByText('NO PURCHASE', { exact: true })).toBeVisible()
  await expect(page.getByText('GoBuy payment is not connected.', { exact: false })).toBeVisible()
  await expect(page.getByText('Authorized limit: 1 SOL', { exact: false })).toBeVisible()
  await expect(page.getByText('PURCHASED ✓', { exact: true })).toHaveCount(0)
})

test('total AI outage shows a safe Na message without raw provider details or fabricated products', async ({ page }) => {
  await page.route('**/api/research/search', route => route.fulfill({ status: 503, contentType: 'application/json',
    body: JSON.stringify({ error: { code: 'ALL_LLM_PROVIDERS_UNAVAILABLE', retryable: true,
      message: "Na's AI providers are temporarily unavailable. Please try again shortly." } }),
  }))
  await page.goto('/na')
  await page.getByLabel('Your request to Na').fill('Find Jordan 1 under 1 SOL')
  await page.getByRole('button', { name: 'Send request', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText("Na's AI providers are temporarily unavailable")
  await expect(page.getByRole('alert')).not.toContainText(/OpenAI|quota|stack/)
  await expect(page.locator('.research-card')).toHaveCount(0)
})
